LeaveManagement/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^apply/for/leave$', views.applying_for_leave, name='leave_application'),
    url(r'^respond/to/leave$', views.responding_to_leave_application, name='responding_to_leave'),

]

app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('LeaveManagement.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
]

LeaveManagement/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

class LeaveRecordDetail(models.Model):
    employee = models.ForeignKey(User, related_name='employee', on_delete=models.CASCADE)
    reporting_manager = models.ForeignKey(User, related_name='reporting_manager' ,on_delete=models.CASCADE)
    sick_leaves = models.PositiveIntegerField(default=14, validators=[MinValueValidator(0)])
    earned_leaves = models.PositiveIntegerField(default=14, validators=[MinValueValidator(0)])
    personal_leaves = models.PositiveIntegerField(default=14, validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.employee) + " " + str(self.reporting_manager)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.sick_leaves < 0 or self.earned_leaves < 0 or self.personal_leaves<0:
            raise Exception
        else:
            super(LeaveRecordDetail,self).save()

    class Meta:
        db_table = 'LeaveRecord'



class LeaveApplication(models.Model):

    TYPES_OF_LEAVES = (
        ('SL', 'SickLeave'),
        ('EL', 'EarnedLeave'),
        ('PL', 'PersonalLeave')
    )

    LEAVE_STATUS = (
        ('U', 'Unresponded'),
        ('A', 'Approved'),
        ('R', 'Rejected'),
    )

    leave_id = models.AutoField(primary_key=True)
    applicant = models.ForeignKey(User, related_name='applicant', on_delete=models.CASCADE)
    approver = models.ForeignKey(User, related_name='approver', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    responded_on = models.DateTimeField(auto_now=True, null=True)
    leave_type = models.CharField(max_length=2, choices=TYPES_OF_LEAVES)
    number_of_days= models.IntegerField()
    from_date = models.DateField()
    to_date = models.DateField()
    leave_status = models.CharField(max_length=1, choices=LEAVE_STATUS, default='U')
    additional_message = models.TextField(max_length=200)

    def __str__(self):
        return self.leave_status

    class Meta:
        db_table = 'LeaveApplication'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        a = LeaveRecordDetail.objects.get(employee = self.applicant)
        if self.applicant == a.employee and self.approver == a.reporting_manager:
            super(LeaveApplication,self).save()
        else:
            raise Exception

LeaveManagement/forms.py
from django import forms
from .models import *

class LeaveApplicationForm(forms.ModelForm):

    class Meta:
        model = LeaveApplication
        fields = "__all__"

LeaveManagement/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required,user_passes_test
from django.http import HttpResponse, HttpResponseRedirect
from .forms import *

@login_required
def index(request):
    return render(request,'lm/base.html')

@login_required
def applying_for_leave(request):
    leave_record = LeaveRecordDetail.objects.get(employee=request.user)
    applicant = request.user
    approver = leave_record.reporting_manager
    if request.method == "GET":
        return render(request, "lm/leave_application_form.html", {"applicant":applicant, "approver":approver})

    if request.method == "POST":
        leave_type = request.POST.get('leave_type')
        num_of_days = int(request.POST.get('num_of_days'))
        from_date = request.POST.get('from_date')
        to_date = request.POST.get('to_date')
        msg = request.POST.get('msg') or None
        try:
            LeaveApplication.objects.create(applicant = applicant, leave_type = leave_type, approver = approver,  number_of_days = num_of_days,from_date = from_date, to_date = to_date, additional_message = msg)
        except Exception as e:
            return render(request, "lm/leave_application_form.html", {"applicant": applicant, "approver": approver,"error":"error"})
        else:
            if leave_type == "EL":
                leave_record.earned_leaves -= num_of_days
                try:
                    leave_record.save()
                except Exception:
                    return render(request, "lm/leave_application_form.html",
                                  {"applicant": applicant, "approver": approver, "error": "error"})
            elif leave_type == "PL":
                leave_record.personal_leaves -= num_of_days
                try:
                    leave_record.save()
                except Exception:
                    return render(request, "lm/leave_application_form.html",
                                  {"applicant": applicant, "approver": approver, "error": "error"})
            else:
                leave_record.sick_leaves -= num_of_days
                try:
                    leave_record.save()
                except Exception:
                    return render(request, "lm/leave_application_form.html",
                                  {"applicant": applicant, "approver": approver, "error": "error"})
            return HttpResponseRedirect(reverse('index'))



@login_required
def responding_to_leave_application(request):

    if request.method == "GET":
        applications = LeaveApplication.objects.filter(approver = request.user, leave_status = 'U')
        return render(request, "lm/responding_to_application.html", {"applications":applications})

    if request.method == "POST":
        leave_id = request.POST.get('leave_id')
        applicant = request.POST.get('applicant')
        num_of_days = request.POST.get('number_of_days')
        leave_type = request.POST.get('leave_type')
        response_type = request.POST.get('submit')
        leave_record = LeaveApplication.objects.get(leave_id=leave_id)
        user = User.objects.get(first_name = applicant)

        if response_type == "R":
            employee_record = LeaveRecordDetail.objects.get(employee = user)
            print(employee_record)
            if leave_type == 'EL':
                employee_record.earned_leaves += int(num_of_days)
                employee_record.save()
            elif leave_type == 'PL':
                employee_record.personal_leaves += int(num_of_days)
                employee_record.save()
            else:
                employee_record.sick_leaves += int(num_of_days)
                employee_record.save()
        leave_record.leave_status = response_type
        leave_record.save()

        return HttpResponseRedirect(reverse('responding_to_leave'))

LeaveManagement/templates/lm/base.html
{% load static %}
<html lang="en">
<head>
    <title>Leave Management</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'lm/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'lm/css/bootstrap.css'%}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'lm/js/app.js'  %}"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lm/js/app.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
    margin-bottom: 0;
    border-radius: 0;
    }
    /* Add a gray background color and some padding to the footer */
    footer {
    background-color: #a7f7f7;
    }
    </style>

    <script>
        function calculate_date(){
            var d = document.getElementById('startdate').value();
            var num_of_days = document.getElementById('num_of_days').value();
            console.write(d);
            console.write(num_of_days);
            d.setDate(d.getDate() + num_of_days);
            document.getElementById("end_date").innerHTML = d;
          }
    </script>
</head>
<body   background="{% static 'lm/image/bgimage.jpg' %}">
    <nav class="navbar navbar-default">
  <div class="container-fluid">


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          {% if not request.user.is_superuser%}
            <li class=""><a href="{% url 'leave_application' %}">Apply</a></li>
          {% endif %}
          {% if request.user.is_staff %}
            <li><a href="{% url 'responding_to_leave' %}">Respond</a></li>
          {% endif %}
        <!--<li ></li>-->
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input class="form-control" placeholder="Search" type="text">
        </div>
        <button type="submit" class="btn btn-default">Go</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

    {% block content %}
    {% endblock %}




</body>
</html>

LeaveManagement/templates/lm/leave_application_form.html
{% extends 'lm/base.html' %}
{% load static %}
{% block content %}

<font color="white" size="4">
<form class="form-horizontal" method="POST" >{% csrf_token %}
  <fieldset>
    <legend><font color="white" size="6">Leave Application Form</font></legend>
      <div class="form-group">
        <label for="applicant" class="col-lg-2 control-label">Applicant</label>
        <div class="col-lg-4">
            <input class="form-control" id="applicant" name="applicant"  value="{{request.user}}" readonly type="text">
        </div>
      </div>
      <div class="form-group">
        <label for="approver" class="col-lg-2 control-label">Approver</label>
        <div class="col-lg-4">
            <input class="form-control" id="approver" name="approver"  value="{{approver}}" readonly type="text">
        </div>
      </div>

      <div class="form-group">
        <label for="leave_type" class="col-lg-2 control-label">Leave Type</label>
      <div class="col-lg-4">
        <select class="form-control" id="leave_type" name="leave_type">
          <option value="SL">Sick Leave</option>
          <option value="EL" selected>Earned Leave</option>
          <option value="PL">Personal Leave</option>
        </select>
        </div>
      </div>
      <div class="form-group">
        <label for="num_of_days" class="col-lg-2 control-label">Number Of Days</label>
        <div class="col-lg-4">
            <input class="form-control" id="num_of_days" name="num_of_days"  type="number" value="2" min="1">
          {% if error %}
          <font color="red" size="3">Insufficient Leaves! For more information contact Admin.</font>
          {% endif %}
        </div>
      </div>

      <div class="form-group">

        <label for="from_date" class="col-lg-2 control-label"  >Start Date</label>
        <div class="col-lg-4">
          <input class="form-control" id="from_date" name="from_date"   type="date" onfocus="datepicker()">
          <span class="help-block"><font color="white" size="4">If using Firefox Date should be in YYYY-MM-DD format.</font></span>
        </div>
      </div>
      <div class="form-group">
        <label for="to_date" class="col-lg-2 control-label">End Date</label>
        <div class="col-lg-4">
            <input class="form-control" id="to_date" name="to_date"  type="date" onblur="calculate_date()">
          <span class="help-block"><font color="white" size="4">If using Firefox Date should be in YYYY-MM-DD format.</font></span>
        </div>
      </div>
      <div class="form-group">
          <label for="msg" class="col-lg-2 control-label">Additional Message</label>
          <div class="col-lg-5">
            <textarea class="form-control" rows="3" id="msg" name="msg" style="resize:none"></textarea>
            <span class="help-block"><font color="white" size="4">If any reason you have to provide.</font></span>
          </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <button type="reset" class="btn btn-warning">Cancel</button>&nbsp;&nbsp;
          <button type="submit" class="btn btn-info">Submit</button>
        </div>
      </div>

  </fieldset>
</form>
</font>
{% endblock %}

LeaveManagement/templates/lm/responding_to_application.html
{% extends 'lm/base.html' %}

{% block content %}
<legend><font color="white" size="6">Respond to Applications</font></legend>

    {% for application in applications%}
    <div style="padding:30px">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">User : {{application.applicant.first_name}}</h3>
            </div>
            <div class="panel-body">
                <table style="text-align:center"  class="table table-striped table-hover ">
                    <thead>
                    <tr>
                        <th style="text-align:center">Leave ID</th>
                        <th style="text-align:center">Number Of days</th>
                        <th style="text-align:center">Leave Type</th>
                        <th style="text-align:center">Leave Status</th>
                        <th style="text-align:center">From date</th>
                        <th style="text-align:center">To date</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr class="active">
                            <td>{{application.leave_id}}</td>
                            <td>{{application.number_of_days}}</td>
                            <td>{{application.get_leave_type_display}}</td>
                            <td>{{application.get_leave_status_display}}</td>
                            <td>{{application.from_date}}</td>
                            <td>{{application.to_date}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <label for="textArea" class="col-lg-2 control-label">Message</label>
                <div style="padding:15px;width:80%">
                    <textarea class="form-control" style="resize:none" rows="3" id="textArea" readonly>{{application.additional_message}}</textarea>
                    <form method="POST">{% csrf_token %}
                        <div class="form-group">
                            <div style="padding-top:15px">
                                <input type="hidden" value="{{application.leave_id}}" name="leave_id" id="leave_id">
                                <input type="hidden" value="{{application.applicant.first_name}}" name="applicant" id="applicant">
                                <input type="hidden" value="{{application.number_of_days}}" name="number_of_days" id="number_of_days">
                                <input type="hidden" value="{{application.leave_type}}" name="leave_type" id="leave_type">
                                <button type="submit" value="A" name="submit" id="submit1" class="btn btn-info">Approve</button>
                                <button type="submit" value="R" name="submit" id="submit2" class="btn btn-warning">Reject</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
{% endblock %}

LeaveManagement/templates/lm/user/leave_application_form.html
{% extends 'lm/base.html' %}

{% block content %}


<form class="form-horizontal" method="POST">{% csrf_token %}
  <fieldset>
    <legend>Leave Application Form</legend>
      <div class="form-group">
        <label for="applicant" class="col-lg-2 control-label">Applicant</label>
        <div class="col-lg-3">
            <input class="form-control" id="applicant" name="applicant"  value="{{request.user}}" readonly type="text">
        </div>
      </div>
      <div class="form-group">
        <label for="approver" class="col-lg-2 control-label">Applicant</label>
        <div class="col-lg-3">
            <input class="form-control" id="approver" name="approver"  value="{{approver}}" readonly type="text">
        </div>
      </div>

      <div class="form-group">
      <label for="select" class="col-lg-2 control-label">Leave Type</label>
      <div class="col-lg-3">
        <select class="form-control" id="select">
          <option value="SL">Sick Leave</option>
          <option value="EL" selected>Earned Leave</option>
          <option value="PL">Personal Leave</option>
        </select>
        </div>
      </div>
      <div class="form-group">
        <label for="num_of_days" class="col-lg-2 control-label">Number Of Days</label>
        <div class="col-lg-3">
            <input class="form-control" id="num_of_days" name="num_of_days"  type="number" value="2" min="1">
        </div>
      </div>
      <div class="form-group">
        <label for="start_date" class="col-lg-2 control-label">Start Date</label>
        <div class="col-lg-3">
            <input class="form-control" id="start_date" name="start_date"  type="datetime" onblur="calculate_date()">
        </div>
      </div>
      <!--<div class="form-group">-->
        <!--<label for="end_date" class="col-lg-2 control-label">End Date</label>-->
        <!--<div class="col-lg-3">-->
            <!--<input class="form-control" id="end_date" name="end_date"  type="datetime" onblur="calculate_date()">-->
        <!--</div>-->
      <!--</div>-->
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <button type="reset" class="btn btn-default">Cancel</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>

  </fieldset>
</form>


<script>

</script>

{% endblock %}